### ISSUE TITLE
User verification fails to add non-existant users.

### ISSUE THREAD

**Issue by fubarhouse** [fubarhouse/golang-drush#37]
```
time="2017-07-19T05:03:50Z" level=error msg="Could not execute Drush sql-query: exit status 1" 
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/fubarhouse/golang-drush/user.(*DrupalUserList).Populate(0xc4200d9c98, 0x0, 0x0)
	/home/vagrant/go/bin/src/github.com/fubarhouse/golang-drush/user/drupal_user_group.go:64 +0x4ec
github.com/fubarhouse/golang-drush/user.(*DrupalUser).Create(0xc4200d9f20, 0x7ffda5affa53, 0xb)
	/home/vagrant/go/bin/src/github.com/fubarhouse/golang-drush/user/drupal_user.go:64 +0x85
main.main()
	/home/vagrant/go/bin/src/github.com/fubarhouse/golang-drush/cmd/user-verify/main.go:65 +0x8b3
exit status 2

```

**Comment by fubarhouse** [comment]
This is now done, took some work though!

New alias creation will run basic validation, 
* defaults are now set which are set with Populate() which result to zero-value with empty results.
* aliases in the user verify binary will now use the alias package, which comes with that additional validation
* aliases not found will report as such
* error creating user will now present stdout
* testing on non-existing and existing user is complete.

Done!
